version: 0.2

phases:
  install:
    commands:
      - echo installing npm and nodejs............
      - apt install npm
      - apt install nodejs

  pre_build:
    commands:
      - echo pre build step running...............
      - npm install

  build:
    commands:
      - echo build step.........
      - npm run build
      - echo build step done.......

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist

  