version: 0.2

phases:

  install:
    commands:

      - echo "installing npm and nodejs............"
      - curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

  pre_build:

    commands:
      - echo "pre build step running..............."
      - npm install

  build:

    commands:

      - echo "build step........."
      - npm run build
      - echo "build step done......."
      - echo "generate....."
      - npm run generate
      - echo "generate done"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist' 
  discard-paths: no
